export const types = [
    {extension: 'html', contentType: 'text/html'},
    {extension: 'htm',  contentType: 'text/html'},
    {extension: 'shtml',contentType: 'text/html'},
    {extension: 'css',  contentType: 'text/css'},
    {extension: 'xml',  contentType: 'text/xml'},
    {extension: 'gif',  contentType: 'image/gif'},
    {extension: 'jpeg', contentType: 'image/jpeg'},
    {extension: 'jpg',  contentType: 'image/jpeg'},
    {extension: 'js',   contentType: 'application/x-javascript'},
    {extension: 'atom', contentType: 'application/atom+xml'},
    {extension: 'rss',  contentType: 'application/rss+xml'},
    {extension: 'mml',  contentType: 'text/mathml'},
    {extension: 'txt',  contentType: 'text/plain'},
    {extension: 'jad',  contentType: 'text/vnd.sun.j2me.app-descriptor'},
    {extension: 'wml',  contentType: 'text/vnd.wap.wml'},
    {extension: 'htc',  contentType: 'text/x-component'},
    {extension: 'png',  contentType: 'image/png'},
    {extension: 'tif',  contentType: 'image/tiff'},
    {extension: 'tiff', contentType: 'image/tiff'},
    {extension: 'wbmp', contentType: 'image/vnd.wap.wbmp'},
    {extension: 'ico',  contentType: 'image/x-icon'},
    {extension: 'jng',  contentType: 'image/x-jng'},
    {extension: 'bmp',  contentType: 'image/x-ms-bmp'},
    {extension: 'svg',  contentType: 'image/svg+xml'},
    {extension: 'webp', contentType: 'image/webp'},
    {extension: '3gpp', contentType: 'video/3gpp'},
    {extension: '3gp',  contentType: 'video/3gpp'},
    {extension: 'mpeg', contentType: 'video/mpeg'},
    {extension: 'mpg',  contentType: 'video/mpeg'},
    {extension: 'mov',  contentType: 'video/quicktime'},
    {extension: 'flv',  contentType: 'video/x-flv'},
    {extension: 'mng',  contentType: 'video/x-mng'},
    {extension: 'asx',  contentType: 'video/x-ms-asf'},
    {extension: 'asf',  contentType: 'video/x-ms-asf'},
    {extension: 'wmv',  contentType: 'video/x-ms-wmv'},
    {extension: 'avi',  contentType: 'video/x-msvideo'},
    {extension: 'm4v',  contentType: 'video/mp4'},
    {extension: 'mp4',  contentType: 'video/mp4'},
    {extension: 'mid',  contentType: 'audio/midi'},
    {extension: 'midi', contentType: 'audio/midi'},
    {extension: 'kar',  contentType: 'audio/midi'},
    {extension: 'mp3',  contentType: 'audio/mpeg'},
    {extension: 'ogg',  contentType: 'audio/ogg'},
    {extension: 'ra',   contentType: 'audio/x-realaudio'},
    {extension: 'bin',  contentType: 'application/octet-stream'},
    {extension: 'exe',  contentType: 'application/octet-stream'},
    {extension: 'dll',  contentType: 'application/octet-stream'},
    {extension: 'deb',  contentType: 'application/octet-stream'},
    {extension: 'dmg',  contentType: 'application/octet-stream'},
    {extension: 'eot',  contentType: 'application/octet-stream'},
    {extension: 'iso',  contentType: 'application/octet-stream'},
    {extension: 'img',  contentType: 'application/octet-stream'},
    {extension: 'msi',  contentType: 'application/octet-stream'},
    {extension: 'msp',  contentType: 'application/octet-stream'},
    {extension: 'msm',  contentType: 'application/octet-stream'},
    {extension: 'jar',  contentType: 'application/java-archive'},
    {extension: 'war',  contentType: 'application/java-archive'},
    {extension: 'ear',  contentType: 'application/java-archive'},
    {extension: 'hqx',  contentType: 'application/mac-binhex40'},
    {extension: 'doc',  contentType: 'application/msword'},
    {extension: 'docx',  contentType: 'application/msword'},
    {extension: 'pdf',  contentType: 'application/pdf'},
    {extension: 'ps',   contentType: 'application/postscript'},
    {extension: 'eps',  contentType: 'application/postscript'},
    {extension: 'ai',   contentType: 'application/postscript'},
    {extension: 'rtf',  contentType: 'application/rtf'},
    {extension: 'xls',  contentType: 'application/vnd.ms-excel'},
    {extension: 'xlsx',  contentType: 'application/vnd.ms-excel'},
    {extension: 'ppt',  contentType: 'application/vnd.ms-powerpoint'},
    {extension: 'wmlc', contentType: 'application/vnd.wap.wmlc'},
    {extension: 'kml',  contentType: 'application/vnd.google-earth.kml+xml'},
    {extension: 'kmz',  contentType: 'application/vnd.google-earth.kmz'},
    {extension: '7z',   contentType: 'application/x-7z-compressed'},
    {extension: 'cco',  contentType: 'application/x-cocoa'},
    {extension: 'jardiff', contentType: 'application/x-java-archive-diff'},
    {extension: 'jnlp', contentType: 'application/x-java-jnlp-file'},
    {extension: 'run',  contentType: 'application/x-makeself'},
    {extension: 'pl',   contentType: 'application/x-perl'},
    {extension: 'pm',   contentType: 'application/x-perl'},
    {extension: 'prc',  contentType: 'application/x-pilot'},
    {extension: 'pdb',  contentType: 'application/x-pilot'},
    {extension: 'rar',  contentType: 'application/x-rar-compressed'},
    {extension: 'rpm',  contentType: 'application/x-redhat-package-manager'},
    {extension: 'sea',  contentType: 'application/x-sea'},
    {extension: 'swf',  contentType: 'application/x-shockwave-flash'},
    {extension: 'sit',  contentType: 'application/x-stuffit'},
    {extension: 'tcl',  contentType: 'application/x-tcl'},
    {extension: 'tk',   contentType: 'application/x-tcl'},
    {extension: 'der',  contentType: 'application/x-x509-ca-cert'},
    {extension: 'pem',  contentType: 'application/x-x509-ca-cert'},
    {extension: 'crt',  contentType: 'application/x-x509-ca-cert'},
    {extension: 'xpi',  contentType: 'application/x-xpinstall'},
    {extension: 'xhtml',contentType: 'application/xhtml+xml'},
    {extension: 'zip',  contentType: 'application/zip'},


    //pdf,xls,xlsx,doc,docx,txt,ods





];
